Repository Tenshi25/CCM2_YuGiOh_Android_Project, pull requests merged in 2020-05, with the labels that each got.

#41 Card monster effect
  .idea/gradle.xml
  app/src/main/java/master/ccm/ccm2yugiohproject/Game_activity.java
  app/src/main/java/master/ccm/entity/subcard/CardInGame.java
  app/src/main/java/master/ccm/entity/subcard/effect/Effect.java
Labels: enhancement

#42 monster cannot activate effect when it is not visible
  app/src/main/java/master/ccm/ccm2yugiohproject/Game_activity.java
Labels: bug

#43 store score of user and display
  app/src/main/java/master/ccm/ccm2yugiohproject/EndGame_activity.java
  app/src/main/java/master/ccm/ccm2yugiohproject/Home.java
  app/src/main/java/master/ccm/entity/Score.java
  app/src/main/java/master/ccm/manager/ScoreDBManager.java
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#44 Http request post
  app/build.gradle
  app/src/main/java/master/ccm/ccm2yugiohproject/Game_activity.java
  app/src/main/java/master/ccm/entity/BattleSystem.java
  app/src/main/java/master/ccm/entity/CardJson.java
  app/src/main/java/master/ccm/entity/Effects/EffectGainPertePV.java
  app/src/main/java/master/ccm/entity/HttpRequest.java
  app/src/main/java/master/ccm/entity/IABot.java
  app/src/main/java/master/ccm/entity/IaDto.java
  app/src/main/java/master/ccm/entity/NameValuePair.java
  app/src/main/java/master/ccm/entity/PileDeCarte/Cimetiere.java
  app/src/main/java/master/ccm/entity/PileDeCarte/Terrain.java
  app/src/main/java/master/ccm/entity/Selection.java
Labels: bug, enhancement
